<a href="https://colab.research.google.com/github/eanzo90/DataAnalysisAndVisualization/blob/main/DataAnalysisAndVisualization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Assignment Title: Data Analysis & Visualization with Python

### Topic: Basic Data Forensics/Exploration

---

### 1. Setup & Load Data

#### Note: Creating a dummy `system_logins.csv` file.

Since the `system_logins.csv` file was not provided, I will create a dummy one for demonstration purposes. **If you have your own `system_logins.csv` file, please upload it to your Colab environment and remove or comment out the following code.**

In [ ]:
# Import necessary libraries for Setup & Load Data
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime, timedelta
import random

# Create a dummy system_logins.csv file for demonstration
num_records = 1000

timestamps = [datetime.now() - timedelta(minutes=random.randint(0, 10000)) for _ in range(num_records)]
user_ids = [f'user_{random.randint(1, 50)}' for _ in range(num_records)]
ip_addresses = [f'{random.randint(1, 255)}.{random.randint(1, 255)}.{random.randint(1, 255)}.{random.randint(1, 255)}' for _ in range(num_records)]
countries = random.choices(['USA', 'Canada', 'UK', 'Germany', 'China', 'India'], k=num_records)
success = random.choices([True, False], weights=[0.85, 0.15], k=num_records)
os = random.choices(['Windows', 'macOS', 'Linux', 'Android', 'iOS'], k=num_records)

dummy_df = pd.DataFrame({
    'timestamp': timestamps,
    'user_id': user_ids,
    'ip_address': ip_addresses,
    'country': countries,
    'success': success,
    'os': os
})
dummy_df.to_csv('system_logins.csv', index=False)

print("Dummy 'system_logins.csv' created.")

# Load system_logins.csv into a DataFrame
try:
    df = pd.read_csv('system_logins.csv')
    print("Successfully loaded 'system_logins.csv'")
except FileNotFoundError:
    print("Error: 'system_logins.csv' not found. Please ensure the file is uploaded or created.")
    # If the file is not found, create an empty DataFrame to avoid further errors
    df = pd.DataFrame(columns=['timestamp', 'user_id', 'ip_address', 'country', 'success', 'os'])

# Display the first few rows of the DataFrame
print("\nDataFrame Head:")
display(df.head())

# Display information about the DataFrame, including data types and non-null values
print("\nDataFrame Info:")
df.info()

Dummy 'system_logins.csv' created.
Successfully loaded 'system_logins.csv'

DataFrame Head:

,timestamp,user_id,ip_address,country,success,os
0,2026-04-20 02:57:01.198409,user_43,125.44.106.85,UK,True,macOS
1,2026-04-21 18:33:01.198434,user_21,129.84.49.150,USA,True,Android
2,2026-04-20 02:36:01.198439,user_36,39.167.205.163,UK,True,Windows
3,2026-04-22 00:20:01.198442,user_11,42.130.160.151,Germany,True,macOS
4,2026-04-24 17:03:01.198444,user_21,174.97.158.30,USA,True,Linux

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   timestamp   1000 non-null   object
 1   user_id     1000 non-null   object
 2   ip_address  1000 non-null   object
 3   country     1000 non-null   object
 4   success     1000 non-null   bool
 5   os          1000 non-null   object
dtypes: bool(1), object(5)
memory usage: 40.2+ KB

### 2. Data Cleaning

In [ ]:
# Check for missing values
print("\nMissing values per column BEFORE cleaning:")
print(df.isnull().sum())

# Convert 'timestamp' column to datetime
df['timestamp'] = pd.to_datetime(df['timestamp'])
print("\n'timestamp' column converted to datetime.")

# Create a new 'hour' column by extracting the hour from the timestamp
df['hour'] = df['timestamp'].dt.hour
print("\n'hour' column created.")

# Display the updated DataFrame info to confirm changes
print("\nDataFrame Info AFTER cleaning:")
df.info()

# Display the first few rows with the new 'hour' column
print("\nDataFrame Head AFTER cleaning:")
display(df.head())

Missing values per column BEFORE cleaning:
timestamp     0
user_id       0
ip_address    0
country       0
success       0
os            0
dtype: int64

'timestamp' column converted to datetime.

'hour' column created.

DataFrame Info AFTER cleaning:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   timestamp   1000 non-null   datetime64[ns]
 1   user_id     1000 non-null   object
 2   ip_address  1000 non-null   object
 3   country     1000 non-null   object
 4   success     1000 non-null   bool
 5   os          1000 non-null   object
 6   hour        1000 non-null   int32
dtypes: bool(1), datetime64[ns](1), int32(1), object(4)
memory usage: 44.1+ KB

DataFrame Head AFTER cleaning:

,timestamp,user_id,ip_address,country,success,os,hour
0,2026-04-20 02:57:01.198409,user_43,125.44.106.85,UK,True,macOS,2
1,2026-04-21 18:33:01.198434,user_21,129.84.49.150,USA,True,Android,18
2,2026-04-20 02:36:01.198439,user_36,39.167.205.163,UK,True,Windows,2
3,2026-04-22 00:20:01.198442,user_11,42.130.160.151,Germany,True,macOS,0
4,2026-04-24 17:03:01.198444,user_21,174.97.158.30,USA,True,Linux,17